[package]
name = "TestPyth"
version = "0.0.1"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet"
override = true

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/move-stdlib"
rev = "mainnet"
override = true

[dependencies.Pyth]
local = "./vendors/pyth"
#git = "https://github.com/pyth-network/pyth-crosschain.git"
#subdir = "target_chains/sui/contracts"
#rev = "sui/hot_potato"

[addresses]
test_pyth = "0x0"
