[package]
name = "X_oracle"
version = "0.0.1"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "testnet" }

[addresses]
x_oracle = "0x0"
x_oracle_v2 = "0x0"
std = "0x1"
sui = "0x2"
